package taiyi.web.dao;

import java.util.List;

import taiyi.web.model.Hostipal;

public interface HostipalMapper {
	List<Hostipal> selectAll();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hostipal
     *
     * @mbggenerated Tue Jul 05 11:19:57 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hostipal
     *
     * @mbggenerated Tue Jul 05 11:19:57 CST 2016
     */
    int insert(Hostipal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hostipal
     *
     * @mbggenerated Tue Jul 05 11:19:57 CST 2016
     */
    int insertSelective(Hostipal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hostipal
     *
     * @mbggenerated Tue Jul 05 11:19:57 CST 2016
     */
    Hostipal selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hostipal
     *
     * @mbggenerated Tue Jul 05 11:19:57 CST 2016
     */
    int updateByPrimaryKeySelective(Hostipal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hostipal
     *
     * @mbggenerated Tue Jul 05 11:19:57 CST 2016
     */
    int updateByPrimaryKey(Hostipal record);
}