package taiyi.web.dao;

import java.util.Set;

import taiyi.web.model.SystemRole;

public interface SystemRoleMapper {
	
	Set<String> selectRoleStringsByUserId(String userId);
	Set<String> selectRoleStringsByUsername(String username);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Tue Jun 07 13:33:39 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Tue Jun 07 13:33:39 CST 2016
     */
    int insert(SystemRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Tue Jun 07 13:33:39 CST 2016
     */
    int insertSelective(SystemRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Tue Jun 07 13:33:39 CST 2016
     */
    SystemRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Tue Jun 07 13:33:39 CST 2016
     */
    int updateByPrimaryKeySelective(SystemRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Tue Jun 07 13:33:39 CST 2016
     */
    int updateByPrimaryKey(SystemRole record);
}