package taiyi.web.dao;

import java.util.List;

import taiyi.web.model.SystemRolePermissionKey;

public interface SystemRolePermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_permission
     *
     * @mbggenerated Tue Jun 07 11:38:58 CST 2016
     */
    int deleteByPrimaryKey(SystemRolePermissionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_permission
     *
     * @mbggenerated Tue Jun 07 11:38:58 CST 2016
     */
    int insert(SystemRolePermissionKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_permission
     *
     * @mbggenerated Tue Jun 07 11:38:58 CST 2016
     */
    int insertSelective(SystemRolePermissionKey record);
    
    List<SystemRolePermissionKey> selectByPermissionId(int permissionId);
    List<SystemRolePermissionKey> selectByRoleId(int roleId);

}