package taiyi.web.dao;

import taiyi.web.model.UserActive;

public interface UserActiveMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_active
	 * @mbg.generated  Tue Sep 13 16:39:56 CST 2016
	 */
	int insert(UserActive record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_active
	 * @mbg.generated  Tue Sep 13 16:39:56 CST 2016
	 */
	int insertSelective(UserActive record);

	int deleteByPrimaryKey(String id);


    UserActive selectByPrimaryKey(String id);

    int updateByPrimaryKeySelective(UserActive record);

    int updateByPrimaryKey(UserActive record);
}