/**
 * 
 */
package taiyi.web.model.dto;

import java.util.Set;

import taiyi.web.model.SystemUser;

/**
 * @author <a href="mailto:jason19659@163.com">jason19659</a>
 *
 *         taiyi.web.model.dto
 *
 *         2016年8月5日
 */
public class SystemUserRoleDto {
	private String id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_user.username
	 *
	 * @mbggenerated Thu Jun 02 15:23:31 CST 2016
	 */
	private String username;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_user.name
	 *
	 * @mbggenerated Thu Jun 02 15:23:31 CST 2016
	 */
	private String name;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_user.hostipal_id
	 *
	 * @mbggenerated Thu Jun 02 15:23:31 CST 2016
	 */
	private Integer hostipalId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_user.department_id
	 *
	 * @mbggenerated Thu Jun 02 15:23:31 CST 2016
	 */
	private Integer departmentId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_user.is_valid
	 *
	 * @mbggenerated Thu Jun 02 15:23:31 CST 2016
	 */
	private Boolean isValid;
	private Set<String> systemRoles;

	/**
	 * @return the systemRoles
	 */
	public Set<String> getSystemRoles() {
		return systemRoles;
	}

	/**
	 * @param systemRoles
	 *            the systemRoles to set
	 */
	public void setSystemRoles(Set<String> systemRoles) {
		this.systemRoles = systemRoles;
	}

	/**
	 * @return the id
	 */
	public String getId() {
		return id;
	}

	/**
	 * @param id the id to set
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * @return the username
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * @param username the username to set
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * @return the name
	 */
	public String getName() {
		return name;
	}

	/**
	 * @param name the name to set
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * @return the hostipalId
	 */
	public Integer getHostipalId() {
		return hostipalId;
	}

	/**
	 * @param hostipalId the hostipalId to set
	 */
	public void setHostipalId(Integer hostipalId) {
		this.hostipalId = hostipalId;
	}

	/**
	 * @return the departmentId
	 */
	public Integer getDepartmentId() {
		return departmentId;
	}

	/**
	 * @param departmentId the departmentId to set
	 */
	public void setDepartmentId(Integer departmentId) {
		this.departmentId = departmentId;
	}

	/**
	 * @return the isValid
	 */
	public Boolean getIsValid() {
		return isValid;
	}

	/**
	 * @param isValid the isValid to set 
	 */
	public void setIsValid(Boolean isValid) {
		this.isValid = isValid;
	}

	
}
