/**
 * 
 */
package taiyi.web.model.dto;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import com.alibaba.fastjson.annotation.JSONField;

import taiyi.web.model.EssUser;

/**
 * @author <a href="mailto:jason19659@163.com">jason19659</a>
 *
 * taiyi.web.model.dto
 *
 * 2016年9月6日
 */
public class UserEssAndDHDto {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbggenerated Thu Jun 02 15:08:20 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.name
     *
     * @mbggenerated Thu Jun 02 15:08:20 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.birthday
     *
     * @mbggenerated Thu Jun 02 15:08:20 CST 2016
     */
    @JSONField(format="yyyy-MM-dd")
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.weight
     *
     * @mbggenerated Thu Jun 02 15:08:20 CST 2016
     */
    private Double weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.height
     *
     * @mbggenerated Thu Jun 02 15:08:20 CST 2016
     */
    private Integer height;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.ess_rank
     *
     * @mbggenerated Thu Jun 02 15:08:20 CST 2016
     */
    private Integer essRank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.account_id
     *
     * @mbggenerated Thu Jun 02 15:08:20 CST 2016
     */
    private String accountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.gender
     *
     * @mbggenerated Thu Jun 02 15:08:20 CST 2016
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.phone
     *
     * @mbggenerated Thu Jun 02 15:08:20 CST 2016
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.address
     *
     * @mbggenerated Thu Jun 02 15:08:20 CST 2016
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.doctor_id
     *
     * @mbggenerated Thu Jun 02 15:08:20 CST 2016
     */
    private String doctorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.register_date
     *
     * @mbggenerated Thu Jun 02 15:08:20 CST 2016
     */
    @JSONField(serialize=false)
    private Date registerDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.lastest_date
     *
     * @mbggenerated Thu Jun 02 15:08:20 CST 2016
     */
    @JSONField(serialize=false)
    private Date lastestDate;
    
    private List<EssUser> ess;
    
    private DiseaseHistoryDto diseaseHistories;

	/**
	 * @return the id
	 */
	public String getId() {
		return id;
	}

	/**
	 * @param id the id to set
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * @return the name
	 */
	public String getName() {
		return name;
	}

	/**
	 * @param name the name to set
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * @return the birthday
	 */
	public Date getBirthday() {
		return birthday;
	}

	/**
	 * @param birthday the birthday to set
	 */
	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	/**
	 * @return the weight
	 */
	public Double getWeight() {
		return weight;
	}

	/**
	 * @param weight the weight to set
	 */
	public void setWeight(Double weight) {
		this.weight = weight;
	}

	/**
	 * @return the height
	 */
	public Integer getHeight() {
		return height;
	}

	/**
	 * @param height the height to set
	 */
	public void setHeight(Integer height) {
		this.height = height;
	}

	/**
	 * @return the essRank
	 */
	public Integer getEssRank() {
		return essRank;
	}

	/**
	 * @param essRank the essRank to set
	 */
	public void setEssRank(Integer essRank) {
		this.essRank = essRank;
	}

	/**
	 * @return the accountId
	 */
	public String getAccountId() {
		return accountId;
	}

	/**
	 * @param accountId the accountId to set
	 */
	public void setAccountId(String accountId) {
		this.accountId = accountId;
	}

	/**
	 * @return the gender
	 */
	public String getGender() {
		return gender;
	}

	/**
	 * @param gender the gender to set
	 */
	public void setGender(String gender) {
		this.gender = gender;
	}

	/**
	 * @return the phone
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * @param phone the phone to set
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * @return the address
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * @param address the address to set
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * @return the doctorId
	 */
	public String getDoctorId() {
		return doctorId;
	}

	/**
	 * @param doctorId the doctorId to set
	 */
	public void setDoctorId(String doctorId) {
		this.doctorId = doctorId;
	}

	/**
	 * @return the registerDate
	 */
	public Date getRegisterDate() {
		return registerDate;
	}

	/**
	 * @param registerDate the registerDate to set
	 */
	public void setRegisterDate(Date registerDate) {
		this.registerDate = registerDate;
	}

	/**
	 * @return the lastestDate
	 */
	public Date getLastestDate() {
		return lastestDate;
	}

	/**
	 * @param lastestDate the lastestDate to set
	 */
	public void setLastestDate(Date lastestDate) {
		this.lastestDate = lastestDate;
	}

	/**
	 * @return the ess
	 */
	public List<EssUser> getEss() {
		return ess;
	}

	/**
	 * @param ess the ess to set
	 */
	public void setEss(List<EssUser> ess) {
		this.ess = ess;
	}

	/**
	 * @return the diseaseHistories
	 */
	public DiseaseHistoryDto getDiseaseHistories() {
		return diseaseHistories;
	}

	/**
	 * @param diseaseHistories the diseaseHistories to set
	 */
	public void setDiseaseHistories(DiseaseHistoryDto diseaseHistories) {
		this.diseaseHistories = diseaseHistories;
	}
    
    
    
}
