package taiyi.web.model;

import java.util.ArrayList;

import org.codehaus.jackson.annotate.JsonIgnore;

public class DiseaseHistory {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column disease_history.id
	 *
	 * @mbggenerated Tue Mar 08 16:09:20 CST 2016
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column disease_history.name
	 *
	 * @mbggenerated Tue Mar 08 16:09:20 CST 2016
	 */
	private String name;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column disease_history.id
	 *
	 * @return the value of disease_history.id
	 *
	 * @mbggenerated Tue Mar 08 16:09:20 CST 2016
	 */
	@JsonIgnore
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column disease_history.id
	 *
	 * @param id
	 *            the value for disease_history.id
	 *
	 * @mbggenerated Tue Mar 08 16:09:20 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column disease_history.name
	 *
	 * @return the value of disease_history.name
	 *
	 * @mbggenerated Tue Mar 08 16:09:20 CST 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column disease_history.name
	 *
	 * @param name
	 *            the value for disease_history.name
	 *
	 * @mbggenerated Tue Mar 08 16:09:20 CST 2016
	 */
	public void setName(String name) {
		this.name = name;
	}

	/*
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "DiseaseHistory [id=" + id + ", name=" + name + "]";
	}

}