package taiyi.web.model;

import java.util.Date;

import com.alibaba.fastjson.annotation.JSONField;

public class Hostipal {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hostipal.id
	 * @mbggenerated  Thu Jul 21 14:54:16 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hostipal.name
	 * @mbggenerated  Thu Jul 21 14:54:16 CST 2016
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hostipal.alias
	 * @mbggenerated  Thu Jul 21 14:54:16 CST 2016
	 */
	private String alias;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hostipal.address
	 * @mbggenerated  Thu Jul 21 14:54:16 CST 2016
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hostipal.phone
	 * @mbggenerated  Thu Jul 21 14:54:16 CST 2016
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hostipal.reg_date
	 * @mbggenerated  Thu Jul 21 14:54:16 CST 2016
	 */
	private Date regDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hostipal.id
	 * @return  the value of hostipal.id
	 * @mbggenerated  Thu Jul 21 14:54:16 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hostipal.id
	 * @param id  the value for hostipal.id
	 * @mbggenerated  Thu Jul 21 14:54:16 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hostipal.name
	 * @return  the value of hostipal.name
	 * @mbggenerated  Thu Jul 21 14:54:16 CST 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hostipal.name
	 * @param name  the value for hostipal.name
	 * @mbggenerated  Thu Jul 21 14:54:16 CST 2016
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hostipal.alias
	 * @return  the value of hostipal.alias
	 * @mbggenerated  Thu Jul 21 14:54:16 CST 2016
	 */
	public String getAlias() {
		return alias;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hostipal.alias
	 * @param alias  the value for hostipal.alias
	 * @mbggenerated  Thu Jul 21 14:54:16 CST 2016
	 */
	public void setAlias(String alias) {
		this.alias = alias;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hostipal.address
	 * @return  the value of hostipal.address
	 * @mbggenerated  Thu Jul 21 14:54:16 CST 2016
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hostipal.address
	 * @param address  the value for hostipal.address
	 * @mbggenerated  Thu Jul 21 14:54:16 CST 2016
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hostipal.phone
	 * @return  the value of hostipal.phone
	 * @mbggenerated  Thu Jul 21 14:54:16 CST 2016
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hostipal.phone
	 * @param phone  the value for hostipal.phone
	 * @mbggenerated  Thu Jul 21 14:54:16 CST 2016
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hostipal.reg_date
	 * @return  the value of hostipal.reg_date
	 * @mbggenerated  Thu Jul 21 14:54:16 CST 2016
	 */
	@JSONField(format="yyyy-MM-dd HH:mm:ss")
	public Date getRegDate() {
		return regDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hostipal.reg_date
	 * @param regDate  the value for hostipal.reg_date
	 * @mbggenerated  Thu Jul 21 14:54:16 CST 2016
	 */
	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}
}