package taiyi.web.model;

import java.util.Date;

import com.alibaba.fastjson.annotation.JSONField;
//import com.fasterxml.jackson.annotation.JsonFormat;

public class SleepReport {
	
	
    private String id;

    private String userId;
    @JSONField(format="yyyy-MM-dd HH:mm:ss")
    private Date startTime;
    @JSONField(format="yyyy-MM-dd HH:mm:ss")
    private Date endTime;

    private Integer lightSleepSeconds;
    
    private Integer deepSleepSeconds;

    private Integer awakeSeconds;

    private Integer totalSeconds;

    private Integer score;
    @JSONField(format="yyyy-MM-dd HH:mm:ss")
    private Date uploadDate;
    
    

    /**
	 * 
	 */
	public SleepReport() {
		super();
	}

	/**
	 * @param id
	 * @param userId
	 * @param startTime
	 * @param endTime
	 * @param lightSleepSeconds
	 * @param deepSleepSeconds
	 * @param awakeSeconds
	 * @param totalSeconds
	 * @param score
	 * @param uploadDate
	 */
	public SleepReport(String id, String userId, Date startTime, Date endTime, Integer lightSleepSeconds,
			Integer deepSleepSeconds, Integer awakeSeconds, Integer totalSeconds, Integer score, Date uploadDate) {
		super();
		this.id = id;
		this.userId = userId;
		this.startTime = startTime;
		this.endTime = endTime;
		this.lightSleepSeconds = lightSleepSeconds;
		this.deepSleepSeconds = deepSleepSeconds;
		this.awakeSeconds = awakeSeconds;
		this.totalSeconds = totalSeconds;
		this.score = score;
		this.uploadDate = uploadDate;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sleep_report.id
     *
     * @return the value of sleep_report.id
     *
     * @mbggenerated Tue Mar 08 16:09:20 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sleep_report.id
     *
     * @param id the value for sleep_report.id
     *
     * @mbggenerated Tue Mar 08 16:09:20 CST 2016
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sleep_report.user_id
     *
     * @return the value of sleep_report.user_id
     *
     * @mbggenerated Tue Mar 08 16:09:20 CST 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sleep_report.user_id
     *
     * @param userId the value for sleep_report.user_id
     *
     * @mbggenerated Tue Mar 08 16:09:20 CST 2016
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sleep_report.start_time
     *
     * @return the value of sleep_report.start_time
     *
     * @mbggenerated Tue Mar 08 16:09:20 CST 2016
     */
//    @JsonFormat(locale="zh", timezone="GMT+8", pattern="yyyy-MM-dd HH:mm:ss")
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sleep_report.start_time
     *
     * @param startTime the value for sleep_report.start_time
     *
     * @mbggenerated Tue Mar 08 16:09:20 CST 2016
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sleep_report.end_time
     *
     * @return the value of sleep_report.end_time
     *
     * @mbggenerated Tue Mar 08 16:09:20 CST 2016
     */
//    @JsonFormat(locale="zh", timezone="GMT+8", pattern="yyyy-MM-dd HH:mm:ss")
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sleep_report.end_time
     *
     * @param endTime the value for sleep_report.end_time
     *
     * @mbggenerated Tue Mar 08 16:09:20 CST 2016
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sleep_report.light_sleep_seconds
     *
     * @return the value of sleep_report.light_sleep_seconds
     *
     * @mbggenerated Tue Mar 08 16:09:20 CST 2016
     */
    public Integer getLightSleepSeconds() {
        return lightSleepSeconds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sleep_report.light_sleep_seconds
     *
     * @param lightSleepSeconds the value for sleep_report.light_sleep_seconds
     *
     * @mbggenerated Tue Mar 08 16:09:20 CST 2016
     */
    public void setLightSleepSeconds(Integer lightSleepSeconds) {
        this.lightSleepSeconds = lightSleepSeconds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sleep_report.deep_sleep_seconds
     *
     * @return the value of sleep_report.deep_sleep_seconds
     *
     * @mbggenerated Tue Mar 08 16:09:20 CST 2016
     */
    public Integer getDeepSleepSeconds() {
        return deepSleepSeconds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sleep_report.deep_sleep_seconds
     *
     * @param deepSleepSeconds the value for sleep_report.deep_sleep_seconds
     *
     * @mbggenerated Tue Mar 08 16:09:20 CST 2016
     */
    public void setDeepSleepSeconds(Integer deepSleepSeconds) {
        this.deepSleepSeconds = deepSleepSeconds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sleep_report.awake_seconds
     *
     * @return the value of sleep_report.awake_seconds
     *
     * @mbggenerated Tue Mar 08 16:09:20 CST 2016
     */
    public Integer getAwakeSeconds() {
        return awakeSeconds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sleep_report.awake_seconds
     *
     * @param awakeSeconds the value for sleep_report.awake_seconds
     *
     * @mbggenerated Tue Mar 08 16:09:20 CST 2016
     */
    public void setAwakeSeconds(Integer awakeSeconds) {
        this.awakeSeconds = awakeSeconds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sleep_report.total_seconds
     *
     * @return the value of sleep_report.total_seconds
     *
     * @mbggenerated Tue Mar 08 16:09:20 CST 2016
     */
    public Integer getTotalSeconds() {
        return totalSeconds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sleep_report.total_seconds
     *
     * @param totalSeconds the value for sleep_report.total_seconds
     *
     * @mbggenerated Tue Mar 08 16:09:20 CST 2016
     */
    public void setTotalSeconds(Integer totalSeconds) {
        this.totalSeconds = totalSeconds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sleep_report.score
     *
     * @return the value of sleep_report.score
     *
     * @mbggenerated Tue Mar 08 16:09:20 CST 2016
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sleep_report.score
     *
     * @param score the value for sleep_report.score
     *
     * @mbggenerated Tue Mar 08 16:09:20 CST 2016
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sleep_report.upload_date
     *
     * @return the value of sleep_report.upload_date
     *
     * @mbggenerated Tue Mar 08 16:09:20 CST 2016
     */
//    @JsonFormat(locale="zh", timezone="GMT+8", pattern="yyyy-MM-dd HH:mm:ss")
    public Date getUploadDate() {
        return uploadDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sleep_report.upload_date
     *
     * @param uploadDate the value for sleep_report.upload_date
     *
     * @mbggenerated Tue Mar 08 16:09:20 CST 2016
     */
    public void setUploadDate(Date uploadDate) {
        this.uploadDate = uploadDate;
    }
}