package taiyi.web.model;

import java.util.Date;

public class SubReport {
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sub_report.id
	 *
	 * @mbg.generated Tue Sep 13 16:47:10 CST 2016
	 */
	private String id;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sub_report.oxygen_reduction_index
	 *
	 * @mbg.generated Tue Sep 13 16:47:10 CST 2016
	 */
	private Double oxygenReductionIndex;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sub_report.longest_apnea_seconds
	 *
	 * @mbg.generated Tue Sep 13 16:47:10 CST 2016
	 */
	private Integer longestApneaSeconds;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sub_report.longest_apnea_time
	 *
	 * @mbg.generated Tue Sep 13 16:47:10 CST 2016
	 */
	private Date longestApneaTime;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sub_report.max_oxygen_reduce_seconds
	 *
	 * @mbg.generated Tue Sep 13 16:47:10 CST 2016
	 */
	private Integer maxOxygenReduceSeconds;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sub_report.max_oxygen_reduce_time
	 *
	 * @mbg.generated Tue Sep 13 16:47:10 CST 2016
	 */
	private Date maxOxygenReduceTime;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sub_report.average_pulse
	 *
	 * @mbg.generated Tue Sep 13 16:47:10 CST 2016
	 */
	private Double averagePulse;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sub_report.max_pulse
	 *
	 * @mbg.generated Tue Sep 13 16:47:10 CST 2016
	 */
	private Double maxPulse;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sub_report.max_pulse_time
	 *
	 * @mbg.generated Tue Sep 13 16:47:10 CST 2016
	 */
	private Date maxPulseTime;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sub_report.min_pulse
	 *
	 * @mbg.generated Tue Sep 13 16:47:10 CST 2016
	 */
	private Double minPulse;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sub_report.min_pulse_time
	 *
	 * @mbg.generated Tue Sep 13 16:47:10 CST 2016
	 */
	private Date minPulseTime;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sub_report.longest_oxygen_reduce_seconds
	 *
	 * @mbg.generated Tue Sep 13 16:47:10 CST 2016
	 */
	private Integer longestOxygenReduceSeconds;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sub_report.longest_oxygen_reduce_time
	 *
	 * @mbg.generated Tue Sep 13 16:47:10 CST 2016
	 */
	private Date longestOxygenReduceTime;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sub_report.blood_oxygen_hazard_index
	 *
	 * @mbg.generated Tue Sep 13 16:47:10 CST 2016
	 */
	private Double bloodOxygenHazardIndex;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sub_report.mac_address
	 *
	 * @mbg.generated Tue Sep 13 16:47:10 CST 2016
	 */
	private String macAddress;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sub_report.advice
	 *
	 * @mbg.generated Tue Sep 13 16:47:10 CST 2016
	 */
	private String advice;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sub_report.perfusion_index
	 *
	 * @mbg.generated Tue Sep 13 16:47:10 CST 2016
	 */
	private Double perfusionIndex;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sub_report.total_apnea_time_seconds
	 *
	 * @mbg.generated Tue Sep 13 16:47:10 CST 2016
	 */
	private Integer totalApneaTimeSeconds;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sub_report.total_hypoventilation_time_seconds
	 *
	 * @mbg.generated Tue Sep 13 16:47:10 CST 2016
	 */
	private Integer totalHypoventilationTimeSeconds;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sub_report.app_version
	 *
	 * @mbg.generated Tue Sep 13 16:47:10 CST 2016
	 */
	private String appVersion;

	public SubReport() {

	}

	/**
	 * @param id
	 * @param oxygenReductionIndex
	 * @param longestApneaSeconds
	 * @param longestApneaTime
	 * @param maxOxygenReduceSeconds
	 * @param maxOxygenReduceTime
	 * @param averagePulse
	 * @param maxPulse
	 * @param maxPulseTime
	 * @param minPulse
	 * @param minPulseTime
	 * @param longestOxygenReduceSeconds
	 * @param longestOxygenReduceTime
	 * @param bloodOxygenHazardIndex
	 * @param macAddress
	 * @param advice
	 * @param perfusionIndex
	 * @param totalApneaTimeSeconds
	 * @param totalHypoventilationTimeSeconds
	 * @param appVersion
	 */
	public SubReport(String id, Double oxygenReductionIndex, Integer longestApneaSeconds, Date longestApneaTime,
			Integer maxOxygenReduceSeconds, Date maxOxygenReduceTime, Double averagePulse, Double maxPulse,
			Date maxPulseTime, Double minPulse, Date minPulseTime, Integer longestOxygenReduceSeconds,
			Date longestOxygenReduceTime, Double bloodOxygenHazardIndex, String macAddress, String advice,
			Double perfusionIndex, Integer totalApneaTimeSeconds, Integer totalHypoventilationTimeSeconds,
			String appVersion) {
		super();
		this.id = id;
		this.oxygenReductionIndex = oxygenReductionIndex;
		this.longestApneaSeconds = longestApneaSeconds;
		this.longestApneaTime = longestApneaTime;
		this.maxOxygenReduceSeconds = maxOxygenReduceSeconds;
		this.maxOxygenReduceTime = maxOxygenReduceTime;
		this.averagePulse = averagePulse;
		this.maxPulse = maxPulse;
		this.maxPulseTime = maxPulseTime;
		this.minPulse = minPulse;
		this.minPulseTime = minPulseTime;
		this.longestOxygenReduceSeconds = longestOxygenReduceSeconds;
		this.longestOxygenReduceTime = longestOxygenReduceTime;
		this.bloodOxygenHazardIndex = bloodOxygenHazardIndex;
		this.macAddress = macAddress;
		this.advice = advice;
		this.perfusionIndex = perfusionIndex;
		this.totalApneaTimeSeconds = totalApneaTimeSeconds;
		this.totalHypoventilationTimeSeconds = totalHypoventilationTimeSeconds;
		this.appVersion = appVersion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sub_report.id
	 *
	 * @return the value of sub_report.id
	 *
	 * @mbg.generated Tue Sep 13 16:47:10 CST 2016
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sub_report.id
	 *
	 * @param id
	 *            the value for sub_report.id
	 *
	 * @mbg.generated Tue Sep 13 16:47:10 CST 2016
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sub_report.oxygen_reduction_index
	 *
	 * @return the value of sub_report.oxygen_reduction_index
	 *
	 * @mbg.generated Tue Sep 13 16:47:10 CST 2016
	 */
	public Double getOxygenReductionIndex() {
		return oxygenReductionIndex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sub_report.oxygen_reduction_index
	 *
	 * @param oxygenReductionIndex
	 *            the value for sub_report.oxygen_reduction_index
	 *
	 * @mbg.generated Tue Sep 13 16:47:10 CST 2016
	 */
	public void setOxygenReductionIndex(Double oxygenReductionIndex) {
		this.oxygenReductionIndex = oxygenReductionIndex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sub_report.longest_apnea_seconds
	 *
	 * @return the value of sub_report.longest_apnea_seconds
	 *
	 * @mbg.generated Tue Sep 13 16:47:10 CST 2016
	 */
	public Integer getLongestApneaSeconds() {
		return longestApneaSeconds;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sub_report.longest_apnea_seconds
	 *
	 * @param longestApneaSeconds
	 *            the value for sub_report.longest_apnea_seconds
	 *
	 * @mbg.generated Tue Sep 13 16:47:10 CST 2016
	 */
	public void setLongestApneaSeconds(Integer longestApneaSeconds) {
		this.longestApneaSeconds = longestApneaSeconds;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sub_report.longest_apnea_time
	 *
	 * @return the value of sub_report.longest_apnea_time
	 *
	 * @mbg.generated Tue Sep 13 16:47:10 CST 2016
	 */
	public Date getLongestApneaTime() {
		return longestApneaTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sub_report.longest_apnea_time
	 *
	 * @param longestApneaTime
	 *            the value for sub_report.longest_apnea_time
	 *
	 * @mbg.generated Tue Sep 13 16:47:10 CST 2016
	 */
	public void setLongestApneaTime(Date longestApneaTime) {
		this.longestApneaTime = longestApneaTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sub_report.max_oxygen_reduce_seconds
	 *
	 * @return the value of sub_report.max_oxygen_reduce_seconds
	 *
	 * @mbg.generated Tue Sep 13 16:47:10 CST 2016
	 */
	public Integer getMaxOxygenReduceSeconds() {
		return maxOxygenReduceSeconds;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sub_report.max_oxygen_reduce_seconds
	 *
	 * @param maxOxygenReduceSeconds
	 *            the value for sub_report.max_oxygen_reduce_seconds
	 *
	 * @mbg.generated Tue Sep 13 16:47:10 CST 2016
	 */
	public void setMaxOxygenReduceSeconds(Integer maxOxygenReduceSeconds) {
		this.maxOxygenReduceSeconds = maxOxygenReduceSeconds;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sub_report.max_oxygen_reduce_time
	 *
	 * @return the value of sub_report.max_oxygen_reduce_time
	 *
	 * @mbg.generated Tue Sep 13 16:47:10 CST 2016
	 */
	public Date getMaxOxygenReduceTime() {
		return maxOxygenReduceTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sub_report.max_oxygen_reduce_time
	 *
	 * @param maxOxygenReduceTime
	 *            the value for sub_report.max_oxygen_reduce_time
	 *
	 * @mbg.generated Tue Sep 13 16:47:10 CST 2016
	 */
	public void setMaxOxygenReduceTime(Date maxOxygenReduceTime) {
		this.maxOxygenReduceTime = maxOxygenReduceTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sub_report.average_pulse
	 *
	 * @return the value of sub_report.average_pulse
	 *
	 * @mbg.generated Tue Sep 13 16:47:10 CST 2016
	 */
	public Double getAveragePulse() {
		return averagePulse;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sub_report.average_pulse
	 *
	 * @param averagePulse
	 *            the value for sub_report.average_pulse
	 *
	 * @mbg.generated Tue Sep 13 16:47:10 CST 2016
	 */
	public void setAveragePulse(Double averagePulse) {
		this.averagePulse = averagePulse;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sub_report.max_pulse
	 *
	 * @return the value of sub_report.max_pulse
	 *
	 * @mbg.generated Tue Sep 13 16:47:10 CST 2016
	 */
	public Double getMaxPulse() {
		return maxPulse;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sub_report.max_pulse
	 *
	 * @param maxPulse
	 *            the value for sub_report.max_pulse
	 *
	 * @mbg.generated Tue Sep 13 16:47:10 CST 2016
	 */
	public void setMaxPulse(Double maxPulse) {
		this.maxPulse = maxPulse;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sub_report.max_pulse_time
	 *
	 * @return the value of sub_report.max_pulse_time
	 *
	 * @mbg.generated Tue Sep 13 16:47:10 CST 2016
	 */
	public Date getMaxPulseTime() {
		return maxPulseTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sub_report.max_pulse_time
	 *
	 * @param maxPulseTime
	 *            the value for sub_report.max_pulse_time
	 *
	 * @mbg.generated Tue Sep 13 16:47:10 CST 2016
	 */
	public void setMaxPulseTime(Date maxPulseTime) {
		this.maxPulseTime = maxPulseTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sub_report.min_pulse
	 *
	 * @return the value of sub_report.min_pulse
	 *
	 * @mbg.generated Tue Sep 13 16:47:10 CST 2016
	 */
	public Double getMinPulse() {
		return minPulse;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sub_report.min_pulse
	 *
	 * @param minPulse
	 *            the value for sub_report.min_pulse
	 *
	 * @mbg.generated Tue Sep 13 16:47:10 CST 2016
	 */
	public void setMinPulse(Double minPulse) {
		this.minPulse = minPulse;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sub_report.min_pulse_time
	 *
	 * @return the value of sub_report.min_pulse_time
	 *
	 * @mbg.generated Tue Sep 13 16:47:10 CST 2016
	 */
	public Date getMinPulseTime() {
		return minPulseTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sub_report.min_pulse_time
	 *
	 * @param minPulseTime
	 *            the value for sub_report.min_pulse_time
	 *
	 * @mbg.generated Tue Sep 13 16:47:10 CST 2016
	 */
	public void setMinPulseTime(Date minPulseTime) {
		this.minPulseTime = minPulseTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sub_report.longest_oxygen_reduce_seconds
	 *
	 * @return the value of sub_report.longest_oxygen_reduce_seconds
	 *
	 * @mbg.generated Tue Sep 13 16:47:10 CST 2016
	 */
	public Integer getLongestOxygenReduceSeconds() {
		return longestOxygenReduceSeconds;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sub_report.longest_oxygen_reduce_seconds
	 *
	 * @param longestOxygenReduceSeconds
	 *            the value for sub_report.longest_oxygen_reduce_seconds
	 *
	 * @mbg.generated Tue Sep 13 16:47:10 CST 2016
	 */
	public void setLongestOxygenReduceSeconds(Integer longestOxygenReduceSeconds) {
		this.longestOxygenReduceSeconds = longestOxygenReduceSeconds;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sub_report.longest_oxygen_reduce_time
	 *
	 * @return the value of sub_report.longest_oxygen_reduce_time
	 *
	 * @mbg.generated Tue Sep 13 16:47:10 CST 2016
	 */
	public Date getLongestOxygenReduceTime() {
		return longestOxygenReduceTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sub_report.longest_oxygen_reduce_time
	 *
	 * @param longestOxygenReduceTime
	 *            the value for sub_report.longest_oxygen_reduce_time
	 *
	 * @mbg.generated Tue Sep 13 16:47:10 CST 2016
	 */
	public void setLongestOxygenReduceTime(Date longestOxygenReduceTime) {
		this.longestOxygenReduceTime = longestOxygenReduceTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sub_report.blood_oxygen_hazard_index
	 *
	 * @return the value of sub_report.blood_oxygen_hazard_index
	 *
	 * @mbg.generated Tue Sep 13 16:47:10 CST 2016
	 */
	public Double getBloodOxygenHazardIndex() {
		return bloodOxygenHazardIndex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sub_report.blood_oxygen_hazard_index
	 *
	 * @param bloodOxygenHazardIndex
	 *            the value for sub_report.blood_oxygen_hazard_index
	 *
	 * @mbg.generated Tue Sep 13 16:47:10 CST 2016
	 */
	public void setBloodOxygenHazardIndex(Double bloodOxygenHazardIndex) {
		this.bloodOxygenHazardIndex = bloodOxygenHazardIndex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sub_report.mac_address
	 *
	 * @return the value of sub_report.mac_address
	 *
	 * @mbg.generated Tue Sep 13 16:47:10 CST 2016
	 */
	public String getMacAddress() {
		return macAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sub_report.mac_address
	 *
	 * @param macAddress
	 *            the value for sub_report.mac_address
	 *
	 * @mbg.generated Tue Sep 13 16:47:10 CST 2016
	 */
	public void setMacAddress(String macAddress) {
		this.macAddress = macAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sub_report.advice
	 *
	 * @return the value of sub_report.advice
	 *
	 * @mbg.generated Tue Sep 13 16:47:10 CST 2016
	 */
	public String getAdvice() {
		return advice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sub_report.advice
	 *
	 * @param advice
	 *            the value for sub_report.advice
	 *
	 * @mbg.generated Tue Sep 13 16:47:10 CST 2016
	 */
	public void setAdvice(String advice) {
		this.advice = advice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sub_report.perfusion_index
	 *
	 * @return the value of sub_report.perfusion_index
	 *
	 * @mbg.generated Tue Sep 13 16:47:10 CST 2016
	 */
	public Double getPerfusionIndex() {
		return perfusionIndex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sub_report.perfusion_index
	 *
	 * @param perfusionIndex
	 *            the value for sub_report.perfusion_index
	 *
	 * @mbg.generated Tue Sep 13 16:47:10 CST 2016
	 */
	public void setPerfusionIndex(Double perfusionIndex) {
		this.perfusionIndex = perfusionIndex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sub_report.total_apnea_time_seconds
	 *
	 * @return the value of sub_report.total_apnea_time_seconds
	 *
	 * @mbg.generated Tue Sep 13 16:47:10 CST 2016
	 */
	public Integer getTotalApneaTimeSeconds() {
		return totalApneaTimeSeconds;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sub_report.total_apnea_time_seconds
	 *
	 * @param totalApneaTimeSeconds
	 *            the value for sub_report.total_apnea_time_seconds
	 *
	 * @mbg.generated Tue Sep 13 16:47:10 CST 2016
	 */
	public void setTotalApneaTimeSeconds(Integer totalApneaTimeSeconds) {
		this.totalApneaTimeSeconds = totalApneaTimeSeconds;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column
	 * sub_report.total_hypoventilation_time_seconds
	 *
	 * @return the value of sub_report.total_hypoventilation_time_seconds
	 *
	 * @mbg.generated Tue Sep 13 16:47:10 CST 2016
	 */
	public Integer getTotalHypoventilationTimeSeconds() {
		return totalHypoventilationTimeSeconds;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column
	 * sub_report.total_hypoventilation_time_seconds
	 *
	 * @param totalHypoventilationTimeSeconds
	 *            the value for sub_report.total_hypoventilation_time_seconds
	 *
	 * @mbg.generated Tue Sep 13 16:47:10 CST 2016
	 */
	public void setTotalHypoventilationTimeSeconds(Integer totalHypoventilationTimeSeconds) {
		this.totalHypoventilationTimeSeconds = totalHypoventilationTimeSeconds;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sub_report.app_version
	 *
	 * @return the value of sub_report.app_version
	 *
	 * @mbg.generated Tue Sep 13 16:47:10 CST 2016
	 */
	public String getAppVersion() {
		return appVersion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sub_report.app_version
	 *
	 * @param appVersion
	 *            the value for sub_report.app_version
	 *
	 * @mbg.generated Tue Sep 13 16:47:10 CST 2016
	 */
	public void setAppVersion(String appVersion) {
		this.appVersion = appVersion;
	}
}