package taiyi.web.model;

public class SystemRolePermissionKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_role_permission.permission_id
	 * @mbggenerated  Tue Jun 07 11:38:58 CST 2016
	 */
	private Long permissionId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_role_permission.role_id
	 * @mbggenerated  Tue Jun 07 11:38:58 CST 2016
	 */
	private Long roleId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_role_permission.permission_id
	 * @return  the value of sys_role_permission.permission_id
	 * @mbggenerated  Tue Jun 07 11:38:58 CST 2016
	 */
	public Long getPermissionId() {
		return permissionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_role_permission.permission_id
	 * @param permissionId  the value for sys_role_permission.permission_id
	 * @mbggenerated  Tue Jun 07 11:38:58 CST 2016
	 */
	public void setPermissionId(Long permissionId) {
		this.permissionId = permissionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_role_permission.role_id
	 * @return  the value of sys_role_permission.role_id
	 * @mbggenerated  Tue Jun 07 11:38:58 CST 2016
	 */
	public Long getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_role_permission.role_id
	 * @param roleId  the value for sys_role_permission.role_id
	 * @mbggenerated  Tue Jun 07 11:38:58 CST 2016
	 */
	public void setRoleId(Long roleId) {
		this.roleId = roleId;
	}
}