package taiyi.web.model;

public class SystemUserRoleKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user_role.role_id
	 * @mbggenerated  Tue Jun 07 11:38:58 CST 2016
	 */
	private Long roleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user_role.user_id
	 * @mbggenerated  Tue Jun 07 11:38:58 CST 2016
	 */
	private String userId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user_role.role_id
	 * @return  the value of sys_user_role.role_id
	 * @mbggenerated  Tue Jun 07 11:38:58 CST 2016
	 */
	public Long getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user_role.role_id
	 * @param roleId  the value for sys_user_role.role_id
	 * @mbggenerated  Tue Jun 07 11:38:58 CST 2016
	 */
	public void setRoleId(Long roleId) {
		this.roleId = roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user_role.user_id
	 * @return  the value of sys_user_role.user_id
	 * @mbggenerated  Tue Jun 07 11:38:58 CST 2016
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user_role.user_id
	 * @param userId  the value for sys_user_role.user_id
	 * @mbggenerated  Tue Jun 07 11:38:58 CST 2016
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}
}