package taiyi.web.model;

public class UserActive {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_active.id
     *
     * @mbg.generated Wed Sep 14 16:32:53 CST 2016
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_active.is_active
     *
     * @mbg.generated Wed Sep 14 16:32:53 CST 2016
     */
    private Boolean isActive;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_active.id
     *
     * @return the value of user_active.id
     *
     * @mbg.generated Wed Sep 14 16:32:53 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_active.id
     *
     * @param id the value for user_active.id
     *
     * @mbg.generated Wed Sep 14 16:32:53 CST 2016
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_active.is_active
     *
     * @return the value of user_active.is_active
     *
     * @mbg.generated Wed Sep 14 16:32:53 CST 2016
     */
    public Boolean getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_active.is_active
     *
     * @param isActive the value for user_active.is_active
     *
     * @mbg.generated Wed Sep 14 16:32:53 CST 2016
     */
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }
}