package taiyi.web.model;

import java.util.Date;
import java.util.List;

import com.alibaba.fastjson.annotation.JSONField;

public class User {
	
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbggenerated Thu Jun 02 15:08:20 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.name
     *
     * @mbggenerated Thu Jun 02 15:08:20 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.birthday
     *
     * @mbggenerated Thu Jun 02 15:08:20 CST 2016
     */
    @JSONField(format="yyyy-MM-dd")
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.weight
     *
     * @mbggenerated Thu Jun 02 15:08:20 CST 2016
     */
    private Double weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.height
     *
     * @mbggenerated Thu Jun 02 15:08:20 CST 2016
     */
    private Integer height;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.ess_rank
     *
     * @mbggenerated Thu Jun 02 15:08:20 CST 2016
     */
    private Integer essRank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.account_id
     *
     * @mbggenerated Thu Jun 02 15:08:20 CST 2016
     */
    private String accountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.gender
     *
     * @mbggenerated Thu Jun 02 15:08:20 CST 2016
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.phone
     *
     * @mbggenerated Thu Jun 02 15:08:20 CST 2016
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.address
     *
     * @mbggenerated Thu Jun 02 15:08:20 CST 2016
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.doctor_id
     *
     * @mbggenerated Thu Jun 02 15:08:20 CST 2016
     */
    @JSONField(serialize=false)
    private String doctorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.register_date
     *
     * @mbggenerated Thu Jun 02 15:08:20 CST 2016
     */
    @JSONField(serialize=false)
    private Date registerDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.lastest_date
     *
     * @mbggenerated Thu Jun 02 15:08:20 CST 2016
     */
    @JSONField(serialize=false)
    private Date lastestDate;
    
    private List<DiseaseHistory> diseaseHistories;

    
	
    /**
	 * @return the diseaseHistories
	 */
	public List<DiseaseHistory> getDiseaseHistories() {
		return diseaseHistories;
	}

	/**
	 * @param diseaseHistories the diseaseHistories to set
	 */
	public void setDiseaseHistories(List<DiseaseHistory> diseaseHistories) {
		this.diseaseHistories = diseaseHistories;
	}


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbggenerated Thu Jun 02 15:08:20 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbggenerated Thu Jun 02 15:08:20 CST 2016
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.name
     *
     * @return the value of user.name
     *
     * @mbggenerated Thu Jun 02 15:08:20 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.name
     *
     * @param name the value for user.name
     *
     * @mbggenerated Thu Jun 02 15:08:20 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.birthday
     *
     * @return the value of user.birthday
     *
     * @mbggenerated Thu Jun 02 15:08:20 CST 2016
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.birthday
     *
     * @param birthday the value for user.birthday
     *
     * @mbggenerated Thu Jun 02 15:08:20 CST 2016
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.weight
     *
     * @return the value of user.weight
     *
     * @mbggenerated Thu Jun 02 15:08:20 CST 2016
     */
    public Double getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.weight
     *
     * @param weight the value for user.weight
     *
     * @mbggenerated Thu Jun 02 15:08:20 CST 2016
     */
    public void setWeight(Double weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.height
     *
     * @return the value of user.height
     *
     * @mbggenerated Thu Jun 02 15:08:20 CST 2016
     */
    public Integer getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.height
     *
     * @param height the value for user.height
     *
     * @mbggenerated Thu Jun 02 15:08:20 CST 2016
     */
    public void setHeight(Integer height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.ess_rank
     *
     * @return the value of user.ess_rank
     *
     * @mbggenerated Thu Jun 02 15:08:20 CST 2016
     */
    public Integer getEssRank() {
        return essRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.ess_rank
     *
     * @param essRank the value for user.ess_rank
     *
     * @mbggenerated Thu Jun 02 15:08:20 CST 2016
     */
    public void setEssRank(Integer essRank) {
        this.essRank = essRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.account_id
     *
     * @return the value of user.account_id
     *
     * @mbggenerated Thu Jun 02 15:08:20 CST 2016
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.account_id
     *
     * @param accountId the value for user.account_id
     *
     * @mbggenerated Thu Jun 02 15:08:20 CST 2016
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.gender
     *
     * @return the value of user.gender
     *
     * @mbggenerated Thu Jun 02 15:08:20 CST 2016
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.gender
     *
     * @param gender the value for user.gender
     *
     * @mbggenerated Thu Jun 02 15:08:20 CST 2016
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.phone
     *
     * @return the value of user.phone
     *
     * @mbggenerated Thu Jun 02 15:08:20 CST 2016
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.phone
     *
     * @param phone the value for user.phone
     *
     * @mbggenerated Thu Jun 02 15:08:20 CST 2016
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.address
     *
     * @return the value of user.address
     *
     * @mbggenerated Thu Jun 02 15:08:20 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.address
     *
     * @param address the value for user.address
     *
     * @mbggenerated Thu Jun 02 15:08:20 CST 2016
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.doctor_id
     *
     * @return the value of user.doctor_id
     *
     * @mbggenerated Thu Jun 02 15:08:20 CST 2016
     */
    public String getDoctorId() {
        return doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.doctor_id
     *
     * @param doctorId the value for user.doctor_id
     *
     * @mbggenerated Thu Jun 02 15:08:20 CST 2016
     */
    public void setDoctorId(String doctorId) {
        this.doctorId = doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.register_date
     *
     * @return the value of user.register_date
     *
     * @mbggenerated Thu Jun 02 15:08:20 CST 2016
     */
    public Date getRegisterDate() {
        return registerDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.register_date
     *
     * @param registerDate the value for user.register_date
     *
     * @mbggenerated Thu Jun 02 15:08:20 CST 2016
     */
    public void setRegisterDate(Date registerDate) {
        this.registerDate = registerDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.lastest_date
     *
     * @return the value of user.lastest_date
     *
     * @mbggenerated Thu Jun 02 15:08:20 CST 2016
     */
    public Date getLastestDate() {
        return lastestDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.lastest_date
     *
     * @param lastestDate the value for user.lastest_date
     *
     * @mbggenerated Thu Jun 02 15:08:20 CST 2016
     */
    public void setLastestDate(Date lastestDate) {
        this.lastestDate = lastestDate;
    }

    
    @JSONField(serialize=false)
    public String getEssResult() {
        String result;
        if (essRank <= 9 ) {
        	result = "正常";
		} else if (essRank >= 10 && essRank <= 13) {
            result = "轻度嗜睡";
        } else if (essRank >= 14 && essRank <= 19) {
            result = "中度嗜睡";
        } else {
            result = "重度嗜睡";
        }
        return result;
    }
	/* 
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "User [id=" + id + ", name=" + name + ", birthday=" + birthday + ", weight=" + weight + ", height="
				+ height + ", essRank=" + essRank + ", accountId=" + accountId + ", gender=" + gender + ", phone="
				+ phone + ", address=" + address + ", doctorId=" + doctorId + ", registerDate=" + registerDate
				+ ", lastestDate=" + lastestDate + ", diseaseHistories=" + diseaseHistories + "]";
	}
    
    
}