package taiyi.web.service;

import taiyi.web.model.BreatheReport;

public interface BreatheReportService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table breathe_report
     *
     * @mbggenerated Tue Mar 08 16:09:20 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table breathe_report
     *
     * @mbggenerated Tue Mar 08 16:09:20 CST 2016
     */
    int insert(BreatheReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table breathe_report
     *
     * @mbggenerated Tue Mar 08 16:09:20 CST 2016
     */
    int insertSelective(BreatheReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table breathe_report
     *
     * @mbggenerated Tue Mar 08 16:09:20 CST 2016
     */
    BreatheReport selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table breathe_report
     *
     * @mbggenerated Tue Mar 08 16:09:20 CST 2016
     */
    int updateByPrimaryKeySelective(BreatheReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table breathe_report
     *
     * @mbggenerated Tue Mar 08 16:09:20 CST 2016
     */
    int updateByPrimaryKey(BreatheReport record);
}