/**
 * 
 */
package taiyi.web.service;

import java.util.List;

import taiyi.web.model.Hostipal;

/**
 * @author <a href="mailto:jason19659@163.com">jason19659</a>
 *
 * taiyi.web.service
 *
 * 2016年7月5日
 */
public interface HostipalService {
	
	List<Hostipal> selectAll();
	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hostipal
     *
     * @mbggenerated Tue Jul 05 11:19:57 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hostipal
     *
     * @mbggenerated Tue Jul 05 11:19:57 CST 2016
     */
    int insert(Hostipal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hostipal
     *
     * @mbggenerated Tue Jul 05 11:19:57 CST 2016
     */
    int insertSelective(Hostipal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hostipal
     *
     * @mbggenerated Tue Jul 05 11:19:57 CST 2016
     */
    Hostipal selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hostipal
     *
     * @mbggenerated Tue Jul 05 11:19:57 CST 2016
     */
    int updateByPrimaryKeySelective(Hostipal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hostipal
     *
     * @mbggenerated Tue Jul 05 11:19:57 CST 2016
     */
    int updateByPrimaryKey(Hostipal record);
}
